/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.*;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Blu-Ray
 */
public class TriangleWindow extends javax.swing.JFrame implements Node {

    Node parent;
    private Color fillcolor;
    private Color bordercolor;

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }

    public TriangleWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        X1Field = new javax.swing.JTextField();
        Y1Field = new javax.swing.JTextField();
        X2Field = new javax.swing.JTextField();
        Y2Field = new javax.swing.JTextField();
        X3Field = new javax.swing.JTextField();
        Y3Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BorderColorButton = new javax.swing.JButton();
        FillColorButton = new javax.swing.JButton();
        TriangleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add Triangle");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("X1");
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        X1Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Y1Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        X2Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Y2Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        X3Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Y3Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Y1");
        jLabel7.setFocusTraversalPolicyProvider(true);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("X2");
        jLabel8.setFocusTraversalPolicyProvider(true);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Y2");
        jLabel9.setFocusTraversalPolicyProvider(true);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("X3");
        jLabel10.setFocusTraversalPolicyProvider(true);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Y3");
        jLabel11.setFocusTraversalPolicyProvider(true);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setOpaque(true);

        BorderColorButton.setBackground(new java.awt.Color(0, 0, 0));
        BorderColorButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BorderColorButton.setForeground(new java.awt.Color(255, 255, 255));
        BorderColorButton.setText("Select Border Color");
        BorderColorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BorderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorderColorButtonActionPerformed(evt);
            }
        });

        FillColorButton.setBackground(new java.awt.Color(0, 0, 0));
        FillColorButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FillColorButton.setForeground(new java.awt.Color(255, 255, 255));
        FillColorButton.setText("Select Fill Color");
        FillColorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillColorButtonActionPerformed(evt);
            }
        });

        TriangleButton.setBackground(new java.awt.Color(0, 0, 0));
        TriangleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TriangleButton.setForeground(new java.awt.Color(255, 255, 255));
        TriangleButton.setText("Create Triangle");
        TriangleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TriangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriangleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BorderColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TriangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(Y3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(X3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Y2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(X2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Y1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(X1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(X1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Y3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorderColorButton)
                    .addComponent(FillColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TriangleButton)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        JFrame parent = (JFrame) this.getParentNode();
        if (parent != null)      //if parent node exists
            parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void BorderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorderColorButtonActionPerformed
        // TODO add your handling code here:\

        Color chosenBorderColor = JColorChooser.showDialog(null, "Select a color", Color.white);
        this.bordercolor = chosenBorderColor;

    }//GEN-LAST:event_BorderColorButtonActionPerformed

    private void FillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillColorButtonActionPerformed
        // TODO add your handling code here:
        MainFrame parent = (MainFrame) this.getParentNode();
        Color chosenFillColor = JColorChooser.showDialog(null, "Select a color", Color.white);
        this.fillcolor = chosenFillColor;
        
           
    }//GEN-LAST:event_FillColorButtonActionPerformed

    private void TriangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriangleButtonActionPerformed
        // TODO add your handling code here:
        MainFrame parent = (MainFrame) this.getParentNode();
        if (X1Field.getText().equals("")) {
            X1Field.setText("Add data here");
        } else if (Y1Field.getText().equals("")) {
            Y1Field.setText("Add data here");
        } else if (X2Field.getText().equals("")) {
            X2Field.setText("Add data here");
        } else if (Y2Field.getText().equals("")) {
            Y2Field.setText("Add data here");
        } else if (X3Field.getText().equals("")) {
            X3Field.setText("Add data here");
        } else if (Y3Field.getText().equals("")) {
            Y3Field.setText("Add data here");
        } else {
            try {

                int x1 = Integer.parseInt(X1Field.getText());
                int y1 = Integer.parseInt(Y1Field.getText());
                int x2 = Integer.parseInt(X2Field.getText());
                int y2 = Integer.parseInt(Y2Field.getText());
                int x3 = Integer.parseInt(X3Field.getText());
                int y3 = Integer.parseInt(Y3Field.getText());
                backend.Triangle T = new backend.Triangle(new Point(x1, y1), new Point(x2, y2), new Point(x3, y3));
                T.setColor(bordercolor);
                T.setFillColor(fillcolor);
                parent.getDrawingArea().addShape(T);
                parent.getDrawingArea().refresh(this.getGraphics());
                parent.getDrawingArea().T++;
                parent.getChooseShapeComboBox().addItem("Triangle" + parent.getDrawingArea().T);
                this.setVisible(false);
                JFrame parentFrame = (JFrame) this.getParentNode();
                if (parentFrame != null) //if parent node exists
                {
                    parentFrame.setVisible(true);
                }
            } catch (NumberFormatException e) {
                if (!parent.isInteger(X1Field.getText())) {
                    X1Field.setText("Not a numeric value.");
                } else if (!parent.isInteger(Y1Field.getText())) {
                    Y1Field.setText("Not a numeric value.");
                } else if (!parent.isInteger(X2Field.getText())) {
                    X2Field.setText("Not a numeric value.");
                } else if (!parent.isInteger(Y2Field.getText())) {
                    Y2Field.setText("Not a numeric value.");
                } else if (!parent.isInteger(X3Field.getText())) {
                    X3Field.setText("Not a numeric value.");
                } else if (!parent.isInteger(Y3Field.getText())) {
                    Y3Field.setText("Not a numeric value.");
                }
            }
        }

    }//GEN-LAST:event_TriangleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorderColorButton;
    private javax.swing.JButton FillColorButton;
    private javax.swing.JButton TriangleButton;
    private javax.swing.JTextField X1Field;
    private javax.swing.JTextField X2Field;
    private javax.swing.JTextField X3Field;
    private javax.swing.JTextField Y1Field;
    private javax.swing.JTextField Y2Field;
    private javax.swing.JTextField Y3Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
